Repository Tech-NYC/Sharity, pull requests merged in 2021-04, with the labels that each got.

#18 feature-knexMigrationsDatabaseConnections
  client/package-lock.json
  connection.js
  index.js
  knexfile.js
  migrations/20210408232745_users.js
  migrations/20210408232811_organizations.js
  migrations/20210408232819_donation_requests.js
  migrations/20210408232830_organization_needs_list.js
  package-lock.json
  package.json
Labels: enhancement

#21 feature-createLoginSignup
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.js
  client/src/Components/auth/Login.js
  client/src/Components/auth/Signup.js
  client/src/Components/home/Navigation.js
  client/src/img/sharitylogo.png
  client/src/img/sharitylogo.svg
  client/src/img/sharitylogobad.svg
Labels: enhancement

#28 feat-CreateListOrgPage
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/public/sharityfavicon.ico
  client/src/App.js
  client/src/Components/OrganizationsList.js
  client/src/Components/auth/Signup.js
Labels: enhancement

#29 feature-styledHomepage
  client/package-lock.json
  client/src/Components/home/Assets/CardItem.js
  client/src/Components/home/Assets/Cards.js
  client/src/Components/home/Header.js
  client/src/Components/home/Impact.js
  client/src/Components/home/Mission.js
  client/src/Components/home/Navigation.js
  client/src/Components/style/Cards.css
  client/src/Components/style/homepage.css
  client/src/Components/style/images/cannedgoods.png
  client/src/Components/style/images/clothesfolded.jpg
  client/src/Components/style/images/donate.jpg
  client/src/Components/style/images/donation.png
  client/src/Components/style/images/furniture.jpg
  client/src/Components/style/images/orgbreakdown.png
  client/src/Components/style/images/yardsale.jpg
Labels: enhancement

#31 (feat) styledHomepage
  client/src/Components/home/Assets/Cards.js
Labels: enhancement

#32 adds mvc controller file structure & middleware folder
  controllers/userController.js
  index.js
  middleware/authentication.js
  migrations/20210408232745_users.js
  migrations/20210408232811_organizations.js
Labels: enhancement

#33 (feat) styled homepage (added files)
  client/src/Components/home/Assets/CardItem.js
  client/src/Components/home/Assets/Cards.js
  client/src/Components/home/Header.js
  client/src/Components/home/Impact.js
  client/src/Components/home/Mission.js
  client/src/Components/style/Cards.css
  client/src/Components/style/homepage.css
  client/src/Components/style/imgs/cannedgoods.png
  client/src/Components/style/imgs/clothesfolded.jpg
  client/src/Components/style/imgs/donate.jpg
  client/src/Components/style/imgs/donation.png
  client/src/Components/style/imgs/furniture.jpg
  client/src/Components/style/imgs/orgbreakdown.png
  client/src/Components/style/imgs/yardsale.jpg
  controllers/userController.js
  middleware/authentication.js
  migrations/20210408232745_users.js
  migrations/20210408232811_organizations.js
  migrations/20210408232819_donation_requests.js
  migrations/20210408232830_organization_needs_list.js
Labels: enhancement

#36 Feature mvc controllers
  controllers/userController.js
  index.js
  middleware/authentication.js
  migrations/20210408232745_users.js
  migrations/20210408232811_organizations.js
Labels: bug, duplicate

#38 Feature mvc controllers
  client/package-lock.json
  controllers/organizationControllers.js
  controllers/userController.js
  index.js
  migrations/20210408232819_donation_requests.js
  migrations/20210408232830_organization_needs_list.js
  package-lock.json
  package.json
Labels: enhancement

#39 (feat) createFooter
  client/package-lock.json
  client/src/Components/Home.js
  client/src/Components/auth/Login.js
  client/src/Components/auth/Signup.js
  client/src/Components/home/Footer.js
  client/src/Components/home/Impact.js
  client/src/Components/home/Mission.js
  client/src/Components/home/Navigation.js
Labels: enhancement

#41 (feat) mvc controllers - adds donateRequest
  .gitignore
  client/package-lock.json
  controllers/donationRequestController.js
  controllers/userController.js
  index.js
  migrations/20210408232819_donation_requests.js
Labels: enhancement

#42 (feat) add organization_needs_list controller
  .gitignore
  controllers/organizationController.js
  controllers/organization_needs_listController.js
  index.js
Labels: enhancement

#44 Feature fix navigation bug
  client/package-lock.json
  client/src/Components/home/Header.js
  client/src/Components/home/Impact.js
  client/src/Components/home/Navigation.js
Labels: bug

#45 (feat) login & registration -donors
  controllers/userController.js
  index.js
  middleware/authentication.js
Labels: enhancement

#49 adds all users and all org needs route
  client/package-lock.json
  controllers/organization_needs_listController.js
  controllers/userController.js
  index.js
Labels: bug, enhancement

#50 adds cors package to index.js
  index.js
  package.json
Labels: enhancement

#52 fixes package-lock issue
  index.js
  package-lock.json
  package.json
Labels: enhancement

#53 change domain name from local host, testing set-cookie
  client/src/Components/auth/Signup.js
  index.js
Labels: enhancement

#56 (feat) - adds organization signup support on serverside, adds organization login data to login response
  controllers/userController.js
  index.js
  middleware/authentication.js
  package-lock.json
Labels: enhancement

#58 create organization registration
  client/src/Components/auth/Signup.js
  client/src/Components/auth/handleStateData.js
Labels: enhancement

#59 Feature create user view org page- still WIP
  client/package-lock.json
  client/src/App.js
  client/src/Components/OrganizationsList.js
  client/src/Components/UserViewOrg.js
  client/src/Components/home/Header.js
  client/src/Components/home/Navigation.js
  client/src/Components/scheduler/ScheduleModal.js
  index.js
  package-lock.json
Labels: enhancement

#61 Bug login username not writeable form
  client/src/Components/auth/Login.js
Labels: bug

#64 Feature create user view org page
  client/src/App.js
  client/src/Components/OrganizationsList.js
  client/src/Components/UserViewOrg.js
Labels: enhancement

#65 add to scheduleModal functionality
  client/src/Components/OrganizationsList.js
  client/src/Components/UserViewOrg.js
  client/src/Components/scheduler/ScheduleModal.js
Labels: enhancement

#67 Feature add terms privacy contact pages
  client/package-lock.json
  client/src/App.js
  client/src/Components/home/Footer.js
  client/src/Components/home/Header.js
  client/src/Components/legal/Contact.js
  client/src/Components/legal/Privacy.js
  client/src/Components/legal/Terms.js
  client/src/Components/style/imgs/contact.jpg
  client/src/Components/style/imgs/contactpic.jpg
Labels: enhancement

#78 adds verbose logging on client side user,org registration and servers…
  client/package-lock.json
  client/src/App.js
  client/src/Components/auth/Signup.js
  client/src/Components/auth/handleStateData.js
  controllers/userController.js
Labels: bug

#79 Fix org creation on all signups
  controllers/userController.js
Labels: bug

#73 (enhancement) comparmentalize registration forms on signup page
  client/src/Components/auth/OrganizationRegistrationForm.js
  client/src/Components/auth/Signup.js
  client/src/Components/auth/UserRegistrationForm.js
Labels: enhancement

#76 resolves 403 error on requesting default avatar for organization
  client/src/Components/UserViewOrg.js
Labels: bug

#80 Feature login redirects to org search page for donators
  client/package-lock.json
  client/src/App.js
  client/src/Components/UserViewOrg.js
  client/src/Components/auth/Login.js
  client/src/Components/home/Navigation.js
  client/src/contexts/UserContext.js
  package-lock.json
Labels: enhancement

#81 Enhancement merge login register response objects
  client/src/Components/auth/Login.js
  client/src/Components/auth/Signup.js
  controllers/userController.js
Labels: enhancement

#82 adds redirect on registration to client signup.js
  client/src/Components/auth/Signup.js
Labels: enhancement

#83 (enhancement) clean up navlinks and navdefaults on pages
  client/src/App.js
  client/src/Components/Home.js
  client/src/Components/OrganizationsList.js
  client/src/Components/UserViewOrg.js
  client/src/Components/auth/Login.js
  client/src/Components/auth/Signup.js
  client/src/Components/home/navlinks.js
  client/src/Components/legal/Contact.js
  client/src/Components/legal/Privacy.js
  client/src/Components/legal/Terms.js
Labels: enhancement

#85 Create org profile
  client/package-lock.json
  client/public/index.html
  client/src/App.js
  client/src/Components/OrganizationsList.js
  client/src/Components/UserViewOrg.js
  client/src/Components/profiles/OrgProfile.js
Labels: bug, enhancement

#87 makes navbar reactive with user auth state
  client/src/App.js
  client/src/Components/UserViewOrg.js
  client/src/Components/auth/Login.js
  client/src/Components/auth/Signup.js
  client/src/Components/home/Navigation.js
  client/src/Components/profiles/OrgProfile.js
Labels: enhancement

#88 Fix fetch org data through context
  client/src/Components/profiles/OrgProfile.js
Labels: bug, enhancement

#89 Enhancement styling consistency
  client/src/Components/OrganizationsList.js
  client/src/Components/home/Navigation.js
Labels: enhancement

#90 adds session state from cookie - missing logout
  client/package-lock.json
  client/src/Components/auth/Login.js
  client/src/Components/auth/Signup.js
  client/src/Components/home/Navigation.js
  client/src/contexts/UserContext.js
  controllers/userController.js
  index.js
Labels: enhancement

#100 attempts logout
  client/src/Components/home/Navigation.js
Labels: enhancement

#101 fix - connects schedule modal to logged in user through user context
  client/src/Components/scheduler/ScheduleModal.js
  controllers/donationRequestController.js
Labels: bug

#103 Fix all orgs render and add tables to org profile
  client/src/Components/OrganizationsList.js
  client/src/Components/profiles/EditProfile.js
  client/src/Components/profiles/OrgProfile.js
Labels: enhancement, fix

#104 Fix donation request creation
  client/src/Components/scheduler/ScheduleModal.js
Labels: enhancement

#105 adds org data to user fetch requests, adds skeleton for org fetch req…
  controllers/userController.js
  index.js
Labels: enhancement

#106 Feature fetch donation requests routes
  controllers/organizationController.js
  controllers/userController.js
  index.js
Labels: enhancement

#107 add user profile page
  client/package-lock.json
  client/src/App.js
  client/src/Components/home/Navigation.js
  client/src/Components/home/navlinks.js
  client/src/Components/profiles/UserProfile.js
Labels: enhancement

#108 (fix) orgcontext placed in comment
  client/src/App.js
  client/src/Components/UserViewOrg.js
  client/src/Components/scheduler/ScheduleModal.js
Labels: enhancement

#109 fixes the org search page
  client/src/Components/OrganizationsList.js
Labels: fix

#111 updates request routes to provide client with request_ids, removed ex…
  client/src/Components/scheduler/ScheduleModal.js
  controllers/organizationController.js
Labels: enhancement

#115 (fix) navbar styling for donate page
  client/src/Components/home/Navigation.js
Labels: bug

#116 Fetching data to tables, wip buttons and edit
  client/src/App.js
  client/src/Components/OrganizationsList.js
  client/src/Components/UserViewOrg.js
  client/src/Components/profiles/EditProfile.js
  client/src/Components/profiles/OrgProfile.js
  client/src/Components/profiles/UserProfile.js
Labels: enhancement

#118 Feature org dashboard accept reject complete requests
  client/package-lock.json
  client/src/App.js
  client/src/Components/home/Navigation.js
  client/src/Components/profiles/OrgProfile.js
  controllers/donationRequestController.js
Labels: enhancement

#120 finished org profile skeleton
  client/src/Components/UserViewOrg.js
  client/src/Components/profiles/EditModal.js
  client/src/Components/profiles/EditProfile.js
  client/src/Components/profiles/UserProfile.js
  client/src/Components/scheduler/ScheduleModal.js
Labels: enhancement, fix

#123 Feature org dashboard accept reject complete requests
  client/src/App.js
  client/src/Components/auth/Login.js
  client/src/Components/home/Navigation.js
  client/src/Components/profiles/OrgProfile.js
  controllers/userController.js
Labels: fix

#125 (feature) route for updating organization profile
  client/package-lock.json
  client/src/Components/profiles/EditModal.js
  controllers/organizationController.js
  index.js
Labels: enhancement

#126 Bug fix login footer and changed contact banner
  client/package-lock.json
  client/src/Components/OrganizationsList.js
  client/src/Components/auth/Login.js
  client/src/Components/legal/Contact.js
  client/src/Components/legal/Terms.js
  client/src/Components/style/imgs/contact-banner2.png
Labels: bug

#127 (enhancement) Add functionality for updating organization profile
  client/package-lock.json
  client/src/Components/profiles/EditModal.js
  controllers/organization_needs_listController.js
  controllers/userController.js
  index.js
Labels: enhancement

#130 updates fetch routes to include date time for donation requests
  client/package-lock.json
  controllers/organizationController.js
Labels: fix

#134 Fix org search page
  client/README.md
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/Components/OrganizationsList.js
  client/src/Components/UserViewOrg.js
  client/src/Components/profiles/EditModal.js
  client/src/Components/profiles/EditProfile.js
  client/src/Components/profiles/OrgProfile.js
  client/src/Components/profiles/UserProfile.js
  client/src/logo.svg
  client/src/setupTests.js
Labels: enhancement, fix

#135 (enhancement) add formatting functions for date and time
  client/package-lock.json
  client/src/Components/UserViewOrg.js
  client/src/Components/home/navlinks.js
  client/src/Components/profiles/EditModal.js
  client/src/Components/profiles/OrgProfile.js
  client/src/Components/profiles/UserProfile.js
  client/src/Components/profiles/parseDateTime.js
Labels: enhancement

#136 (fix) add linkstyle to navigation components
  client/src/Components/home/Navigation.js
Labels: enhancement

#137 (fix) time formatting for organization profile, and made user profile images larger
  client/src/Components/profiles/EditProfile.js
  client/src/Components/profiles/OrgProfile.js
  client/src/Components/profiles/UserProfile.js
  client/src/Components/profiles/parseDateTime.js
Labels: enhancement

#138 (fix) mui styling on uservieworg page
  client/src/Components/UserViewOrg.js
  client/src/Components/profiles/OrgProfile.js
  client/src/index.js
Labels: fix

#139 (fix) page styling
  client/src/Components/OrganizationsList.js
  client/src/Components/UserViewOrg.js
  client/src/Components/profiles/EditProfile.js
  client/src/Components/profiles/OrgProfile.js
  client/src/Components/profiles/UserProfile.js
  client/src/index.js
Labels: enhancement

#140 made the footer a div
  client/src/App.js
  client/src/Components/search/OrganizationsList.js
  client/src/Components/search/style/Search.css
Labels: enhancement, fix

#142 Feature home styling overhaul
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/Components/home/Header.js
  client/src/Components/home/Impact.js
  client/src/Components/home/Mission.js
  client/src/Components/home/Navigation.js
  client/src/Components/map/Map.js
  client/src/Components/style/homepage.css
  client/src/Components/style/imgs/mission.svg
  client/src/index.js
Labels: enhancement

#145 Cleanup inline styling
  client/src/Components/Home.js
  client/src/Components/UserViewOrg.js
  client/src/Components/auth/Login.js
  client/src/Components/auth/OrganizationRegistrationForm.js
  client/src/Components/auth/Signup.js
  client/src/Components/auth/UserRegistrationForm.js
  client/src/Components/home/Footer.js
  client/src/Components/home/Header.js
  client/src/Components/home/Navigation.js
  client/src/Components/legal/Contact.js
  client/src/Components/legal/Terms.js
  client/src/Components/profiles/EditProfile.js
  client/src/Components/profiles/OrgProfile.js
  client/src/Components/profiles/UserProfile.js
  client/src/Components/search/OrganizationsList.js
  client/src/Components/search/style/Search.css
Labels: enhancement, fix

#146 Feature home styling overhaul
  client/src/Components/auth/OrganizationRegistrationForm.js
  client/src/Components/auth/Signup.js
  client/src/Components/home/Header.js
  client/src/Components/home/Impact.js
  client/src/Components/home/Loading.js
  client/src/Components/home/Mission.js
  client/src/Components/home/Navigation.js
  client/src/Components/map/map.css
  client/src/Components/style/homepage.css
  client/src/Components/style/imgs/handoff.svg
Labels: enhancement

#147 Feature styling quirks across site final pass
  client/src/Components/UserViewOrg.js
  client/src/Components/auth/Signup.js
  client/src/Components/legal/Privacy.js
  client/src/Components/profiles/EditProfile.js
  client/src/Components/profiles/OrgProfile.js
  client/src/Components/profiles/UserProfile.js
  client/src/Components/scheduler/ScheduleModal.js
Labels: enhancement
